# Generated by Django 2.1.7 on 2019-03-24 01:34

import books.models
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publishers', '0001_initial'),
        ('categories', '0001_initial'),
        ('physicalformats', '0001_initial'),
        ('series', '0001_initial'),
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الكتاب')),
                ('serie_number', models.IntegerField(blank=True, null=True, verbose_name='رقم السلسلة')),
                ('isbn', models.CharField(max_length=13, verbose_name='الرقم الدولي')),
                ('edition', models.CharField(blank=True, max_length=200, null=True, verbose_name='الطبعة')),
                ('description', models.TextField(blank=True, verbose_name='تفصيل')),
                ('front_image', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='صورة أمامية')),
                ('back_image', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='صورة خلفية')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='الثمن')),
                ('y_dimension', models.IntegerField(default=25, verbose_name='طول الكتاب')),
                ('x_dimension', models.IntegerField(default=20, verbose_name='عرض الكتاب')),
                ('pages', models.IntegerField(verbose_name='عدد الصفحات')),
                ('is_published', models.BooleanField(default=True, verbose_name='منشور؟')),
                ('is_available', models.BooleanField(default=True, verbose_name='موجود؟')),
                ('date_published', models.PositiveIntegerField(default=books.models.get_current_year, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='سنة الإصدار')),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False, verbose_name='تاريخ الإضافة')),
                ('authors', models.ManyToManyField(to='authors.Author', verbose_name='أسماء المؤلفين')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.Category', verbose_name='تصنيف الكتاب')),
                ('physical_format', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='physicalformats.PhysicalFormat', verbose_name='نوع الكتاب')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='publishers.Publisher', verbose_name='الناشر')),
                ('serie', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='series.Serie', verbose_name='السلسلة')),
            ],
            options={
                'verbose_name': 'كتاب',
                'verbose_name_plural': 'كتب',
            },
        ),
    ]
