# Generated by Django 2.1.7 on 2020-01-05 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('keywords', '0001_initial'),
        ('books', '0002_auto_20191230_2054'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='book',
        #     name='keywords',
        #     field=models.ManyToManyField(to='keywords.Keyword', verbose_name='كلمات المفاتيح'),
        # ),
    ]
