# Generated by Django 2.1.7 on 2020-01-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='short_title',
            field=models.CharField(blank=True, max_length=58, verbose_name='عنوان صغير'),
        ),
    ]
