# Generated by Django 2.1.7 on 2020-02-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_short_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='short_title',
            field=models.CharField(blank=True, max_length=58, verbose_name='عنوان قصير'),
        ),
    ]
