# Generated by Django 2.1.7 on 2021-03-07 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20200223_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='publishers.Publisher', verbose_name='الناشر'),
        ),
        migrations.AlterField(
            model_name='book',
            name='x_dimension',
            field=models.IntegerField(default=17, verbose_name='عرض الكتاب'),
        ),
        migrations.AlterField(
            model_name='book',
            name='y_dimension',
            field=models.IntegerField(default=24, verbose_name='طول الكتاب'),
        ),
    ]
