# Generated by Django 2.1.7 on 2019-03-24 01:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الإسم')),
                ('file', models.FileField(upload_to='photos/%Y/%m/%d/', verbose_name='الملف')),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False, verbose_name='تاريخ الإضافة')),
            ],
            options={
                'verbose_name': 'قائمة',
                'verbose_name_plural': 'قوائم',
            },
        ),
    ]
