# Generated by Django 2.1.7 on 2019-03-24 01:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الإسم')),
                ('logo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='الصورة')),
                ('description', models.TextField(blank=True, verbose_name='التفصيل')),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False)),
            ],
            options={
                'verbose_name': 'تصنيف',
                'verbose_name_plural': 'تصنيفات',
            },
        ),
    ]
